# Generated by Django 5.2 on 2025-05-01 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('To Do', 'To Do'), ('In Progress', 'In Progress'), ('pending', 'pending'), ('Completed', 'Completed')], default='To Do', max_length=20),
        ),
    ]
