# Generated by Django 5.2 on 2025-05-02 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('To Do', 'To Do'), ('In Progress', 'In Progress'), ('Pending', 'Pending'), ('Completed', 'Completed')], default='To Do', max_length=20),
        ),
    ]
